----------------------------------------------------------
--修 改 日 期：2021-04-15
--修  改   人：王子明
--备       注: 来料区域配置新增叫料数量字段
----------------------------------------------------------


ALTER TABLE ILT_OPRSEQUENCE_WAREHOUSE_ZX
    ADD MATERIALQUANTITY NVARCHAR2(4);
COMMENT ON COLUMN "ILT_OPRSEQUENCE_WAREHOUSE_ZX".MATERIALQUANTITY IS '叫料数量';
ALTER TABLE ILT_OPRSEQUENCE_WAREHOUSE_ZX
    DROP COLUMN MATERIALQUANTITY;
ALTER TABLE ILT_OPRSEQUENCE_WAREHOUSE_ZX
    MODIFY MATERIALQUANTITY DEFAULT NULL;



ALTER TABLE ILT_OPRSEQUENCE_WAREHOUSE_ZX
    MODIFY MATERIALQUANTITY NVARCHAR2(10);