-- 信息看板库存查询
SELECT
    C.CONTAINER,
    C.QUANTITY AS QUANTITY,
    P.PRODUCTNO,
    IPF.PRODUCTALIAS,              --物料简码
    TT1.MEDIUM AS PRODUCTNAME,
    IA.WIPORDERNO,
    IA.OPRSEQUENCENO,
    TT2.MEDIUM AS OPRSEQUENCENAME, --工序名
    C.SERIALNO AS SERIALNO
FROM
    (
        SELECT
            SIA.CONTAINER,
            SIA.INVENTORYALLOCATIONID,
            SIA.PRODUCTID,
            NVL(SUM(SIA.QUANTITY), 0)  AS QUANTITY,
            LISTAGG(SIA.SERIALNO, ',') AS SERIALNO
        FROM
            SOFT_INVENTORY2_ALLOCATION SIA
        GROUP BY
            SIA.CONTAINER,
            SIA.INVENTORYALLOCATIONID,
            SIA.PRODUCTID
    )                         C
        LEFT JOIN
        INVENTORY2_ALLOCATION IA
        ON C.INVENTORYALLOCATIONID = IA.ID
        LEFT JOIN
        PRODUCT               P
        ON P.ID = C.PRODUCTID
        LEFT JOIN
        TEXT_TRANSLATION      TT1
        ON TT1.TEXTID = P.TEXTID
            AND TT1.LANGUAGEID = '2052'
        LEFT JOIN
        WIP_OPERATION         WO
        ON WO.WIPORDERNO = IA.WIPORDERNO
            AND WO.OPRSEQUENCENO = IA.OPRSEQUENCENO
        LEFT JOIN
        TEXT_TRANSLATION      TT2
        ON TT2.TEXTID = WO.TEXTID
            AND TT2.LANGUAGEID = '2052'
        LEFT JOIN
        ILT_PRODUCT_FACILITY  IPF
        ON IPF.PRODUCTNO = P.PRODUCTNO
WHERE
    C.CONTAINER = 'BK00000422';
--AND IPF.FACILITY ='5802';