SELECT IPC.ID     AS CONTACTID,--物料-料框类型对应关系ID
       P.PRODUCTNO,--物料编码
       TT1.MEDIUM AS PRODUCTNAME, --物料名称
       CC.NAME    AS CONTAINERCLASSNAME,--料框类型编码
       TT2.MEDIUM AS CONTAINERNAME,--料框类型名称
       IPC.LASTUPDATEDBY,--更新人
       IPC.LASTUPDATEON,--更新时间
       IPC.CREATEDBY,--创建人
       IPC.CREATEDON--创建时间
FROM ILT_PRODUCT_CONTAINERCLASS     IPC
         LEFT JOIN PRODUCT          P
         ON IPC.PRODUCTID = P.ID
         LEFT JOIN CONTAINER_CLASS  CC
         ON IPC.CONTAINERCLASSID = CC.ID
         LEFT JOIN TEXT_TRANSLATION TT1
         ON (P.TEXTID = TT1.TEXTID
             AND TT1.LANGUAGEID = @LANGUAGEID)
         LEFT JOIN TEXT_TRANSLATION TT2
         ON (CC.TEXTID = TT2.TEXTID
             AND TT2.LANGUAGEID = @LANGUAGEID)
WHERE IPC.ACTIVE = 1