SELECT
  ROWNUM AS ROWNUMINDEX,
  --入库类型（手动入库，自动入库）
  CASE WHEN TSK_SOURCE IS NULL THEN '自动入库'
    ELSE '手动入库' END TSK_SOURCE ,
  --入库单据号
  IOH.ORDERNO,
  --订单号,
  IOD.WIPORDERNO,
  --工厂
  IOH.PARAMRSRV2,
  --打印状态
  IOH. FACILITY,
  --料框
  --IOH. CONTAINER,
  --请求入库料点
  IOH.FROMLOCATION,
  --入库仓库
  IOH.DISTRIBUTINGWAREHOUSE,
  --单据状态
  CASE WHEN OH.PROGRESSSTATUS=200 THEN '创建'
       WHEN OH.PROGRESSSTATUS=231 THEN '失败'
       WHEN OH.PROGRESSSTATUS=210 THEN '开始执行'
       WHEN OH.PROGRESSSTATUS=220 THEN '起点完成'
        ELSE '完成' END STATUS,
  --备注
  IOH.PARAMRSRV1,
  --创建人
  IOH.CREATEDBY,
  EY.NAME,
  --创建时间
  IOH.CREATEDON,

   --物料编码
  P .PRODUCTNO,
   --物料简码
   IPF.PRODUCTALIAS,
  --物料描述
  TT. MEDIUM AS PRODUCTDES,
  --数量
  OD.QUANTITYORDERED,
  --SN
  SERIALNO,
  --料框编码
  CASE WHEN IOH.TSK_SOURCE=1 THEN
    IOD.TOWAREHOUSECONTAINER
  ELSE IOH.CONTAINER END  CONTAINER
FROM
  ILT_ORDER_HEADER IOH
JOIN ORDER_HEADER OH ON IOH.ORDERNO = OH.ORDERNO AND OH.ACTIVE=1
LEFT JOIN ILT_ORDER_DETAIL IOD ON OH.ORDERNO = IOD.ORDERNO
AND OH.ORDERTYPE = IOD.ORDERTYPE AND IOD.ACTIVE=1
LEFT JOIN ORDER_DETAIL OD ON IOD.ORDERNO = OD.ORDERNO AND IOD.ORDERTYPE= OD.ORDERTYPE
AND IOD.ORDERLINENO = OD.ORDERLINENO
LEFT JOIN EMPLOYEE EY ON IOH.CREATEDBY =EY.EMPLOYEENO
LEFT JOIN PRODUCT P ON OD.PRODUCTID = P.ID
LEFT JOIN TEXT_TRANSLATION TT ON P.TEXTID = TT.TEXTID
AND TT.LanguageID= '2052'
LEFT JOIN ILT_PRODUCT_FACILITY IPF ON P.PRODUCTNO=IPF.PRODUCTNO AND IPF.FACILITY = @Facility
WHERE
  --类型为入库
  IOH.TASKTYPE = 5
  AND TSK_SOURCE IS NULL
  AND IOH.ACTIVE =1
  {SqlFilter}


union all

SELECT
  ROWNUM AS ROWNUMINDEX,
  --入库类型（手动入库，自动入库）
  CASE WHEN TSK_SOURCE IS NULL THEN '自动入库'
    ELSE '手动入库' END TSK_SOURCE ,
  --入库单据号
  IOH.ORDERNO,
  --订单号,
  IOD.WIPORDERNO,
  --工厂
   IOH.PARAMRSRV2,
  --打印状态
  IOH. FACILITY,
  --料框
  --IOH. CONTAINER,
  --请求入库料点
  IOH.FROMLOCATION,
  --入库仓库
  IOH.DISTRIBUTINGWAREHOUSE,
  --单据状态
  CASE WHEN OH.ORDERSTATUS=1 THEN '创建'
       WHEN OH.ORDERSTATUS=7 THEN '已发布'
       WHEN OH.ORDERSTATUS=5 THEN '已删除'
       WHEN OH.ORDERSTATUS=3 THEN '已入库'
        ELSE '拒收' END  STATUS,
   --备注
  IOH.PARAMRSRV1,
  --创建人
  IOH.CREATEDBY,
  EY.NAME,
  --创建时间
  IOH.CREATEDON,

   --物料编码
  P .PRODUCTNO,
  --物料描述
  IPF.PRODUCTALIAS,
  --物料简码
  TT. MEDIUM AS PRODUCTDES,
  --数量
  OD.QUANTITYORDERED,
  --SN
  SERIALNO,
  --料框编码
  CASE WHEN IOH.TSK_SOURCE=1 THEN
    IOD.TOWAREHOUSECONTAINER
  ELSE IOH.CONTAINER END  CONTAINER
FROM
  ILT_ORDER_HEADER IOH
JOIN ORDER_HEADER OH ON IOH.ORDERNO = OH.ORDERNO AND OH.ACTIVE=1
LEFT JOIN ILT_ORDER_DETAIL IOD ON OH.ORDERNO = IOD.ORDERNO AND IOD.ACTIVE=1
AND OH.ORDERTYPE = IOD.ORDERTYPE
LEFT JOIN ORDER_DETAIL OD ON IOD.ORDERNO = OD.ORDERNO AND IOD.ORDERTYPE= OD.ORDERTYPE
AND IOD.ORDERLINENO = OD.ORDERLINENO
LEFT JOIN EMPLOYEE EY ON IOH.CREATEDBY =EY.EMPLOYEENO
LEFT JOIN PRODUCT P ON OD.PRODUCTID = P.ID
LEFT JOIN TEXT_TRANSLATION TT ON P.TEXTID = TT.TEXTID
AND TT.LanguageID= '2052'
LEFT JOIN ILT_PRODUCT_FACILITY IPF ON P.PRODUCTNO=IPF.PRODUCTNO AND IPF.FACILITY = @Facility
WHERE
  --类型为入库
  IOH.TASKTYPE = 5
  AND TSK_SOURCE = '1'
  AND IOH.ACTIVE =1
  AND IOD.WIPORDERNO IS NOT NULL
  {SqlFilter}