SELECT
    ROWNUM            AS ROWSID,
    IRSH.WIPORDERNO,
    IPF.PRODUCTALIAS,
    P.PRODUCTNO,
    IWO.SAPWORKCENTER,
    IW.PUTAWAYLOCATION,
    TT_P.MEDIUM       AS PRODUCTDESC,
    IRSH.WIPOPRSEQUENCENO,
    TT_WOP.MEDIUM     AS OPRSEQUENCENODESC,
    TT.MEDIUM         AS PROGRESSDESC, --SAP报工状态
    IW.MRPCONTROL,
    WO.PRODUCTIONLINENO,
    TT_WL.MEDIUM      AS PRODUCTIONLINEDESC,

    IRSH.PRESTARTDATE,
    IRSH.COMPLETEDATE AS COMPLETEDATE,
    IRSH.GOODQUANTITY,
    IRSH.FIXQUANTITY,
    IRSH.CREATEDBY,
    IRSH.EMPLOYEENAME,
    IRSH.RETURNCONTENT,
    IRSH.RETURNMSG,
    IRSH.SEQUENCENO,
    IRSH.STARTTIME,
    IRSH.COMPLETEDATE AS COMPLETETIME,
    CASE
        WHEN IWO.REPROTSAPSTATUS = 165
            THEN 0
            ELSE 1
        END              READONLY,
    IRSH.SERIALNO,
    E.EMPLOYEENO
FROM
    ILT_REPORT_SAP_HIS                 IRSH
        JOIN      WIP_ORDER            WO
                  ON WO.WIPORDERNO = IRSH.WIPORDERNO

        JOIN      ILT_WIP_ORDER        IW
                  ON WO.WIPORDERNO = IW.WIPORDERNO
                      AND WO.WIPORDERTYPE = IW.WIPORDERTYPE
        LEFT JOIN WIP_LINE             WL
                  ON WL.PRODUCTIONLINENO = WO.PRODUCTIONLINENO
        LEFT JOIN TEXT_TRANSLATION     TT_WL
                  ON WL.TEXTID = TT_WL.TEXTID
                      AND TT_WL.LANGUAGEID = '2052'

        LEFT JOIN WIP_OPERATION        WOP
                  ON IRSH.WIPORDERNO = WOP.WIPORDERNO
                      AND IRSH.WIPOPRSEQUENCENO = WOP.OPRSEQUENCENO
        LEFT JOIN ILT_WIP_OPERATION    IWO
                  ON WOP.WIPORDERNO = IWO.WIPORDERNO
                      AND WOP.WIPORDERTYPE = IWO.WIPORDERTYPE
                      AND WOP.OPRSEQUENCENO = IWO.OPRSEQUENCENO
        LEFT JOIN PROGRESS_STATUS      PS
                  ON IRSH.REPROTSAPSTATUS = PS.PROGRESSSTATUS
        LEFT JOIN TEXT_TRANSLATION     TT
                  ON PS.TEXTID = TT.TEXTID
                      AND TT.LANGUAGEID = '2052'
        LEFT JOIN PRODUCT              P
                  ON P.ID = WO.PRODUCTID
        LEFT JOIN TEXT_TRANSLATION     TT_P
                  ON P.TEXTID = TT_P.TEXTID
                      AND TT_P.LANGUAGEID = '2052'
        LEFT JOIN TEXT_TRANSLATION     TT_WOP
                  ON WOP.TEXTID = TT_WOP.TEXTID
                      AND TT_WOP.LANGUAGEID = '2052'
        LEFT JOIN ILT_PRODUCT_FACILITY IPF
                  ON P.PRODUCTNO = IPF.PRODUCTNO
                      AND IPF.FACILITY = '1820'
        LEFT JOIN EMPLOYEE             E
                  ON E.NAME = IRSH.EMPLOYEENAME
WHERE
    IRSH.REPROTSAPSTATUS = '160'