SELECT
	IOC.FACILITY,
	IOC.WORKCENTER,
	TT.MEDIUM AS WORKCENTERTEXT,
	IOC.OPERATIONNAME,
	IOC.WORKSTATION,
	IOC.EQUIPMENT,
	IOC.CONFIGTYPE AS CONFIGTYPENO,
	IOC.CONFIGTYPE
FROM
	ILT_OPERATION_CONFIG IOC
LEFT JOIN WORK_CENTER WC ON IOC.WORKCENTER = WC.WORKCENTER
LEFT JOIN TEXT_TRANSLATION TT ON WC.TEXTID = TT.TEXTID AND TT.LANGUAGEID = '2052'
WHERE
	IOC.WORKCENTER = '5802-105429' --AND IOC.OPERATIONNAME = '覆盖件总成' AND IOC.CONFIGTYPE = 5
	;

SELECT *
FROM
    ILT_OPERATION_CONFIG;