SELECT WIPORDERNO
FROM (
         SELECT WOP.WIPORDERNO
         FROM WIP_OPERATION WOP
                  JOIN ILT_WIP_ORDER IWO ON WOP.WIPORDERNO = IWO.WIPORDERNO AND WOP.WIPORDERTYPE = IWO.WIPORDERTYPE
         WHERE WOP.WORKCENTER = @WorkCenter
           AND WOP.PROGRESSSTATUS IN (120, 130)
           AND IWO.AS_FLAG = 1
           AND WOP.SCHEDULEDSTARTDATE > SYSDATE - @SchedualStartDateSpan
           AND WOP.SCHEDULEDSTARTDATE < SYSDATE + @SchedualStartDateSpan
           AND WOP.WIPORDERNO <> @WipOrderNo
           AND WOP.SCHEDULEDSTARTDATE < @SCHEDULEDSTARTDATE
         ORDER BY WOP.SCHEDULEDSTARTDATE
     )
WHERE ROWNUM = 1;


-- 获取工位、计划时间
SELECT WOP.PROGRESSSTATUS,
       WOP.WipOrderNo,
       WOP.WipOrderType,
       WOP.OprsequenceNo,
       IWOP.SAPWORKCENTER AS SAPWORKCENTER,
       WOP.WORKCENTER     AS WOPWORKCENTER,
       WOP.SCHEDULEDSTARTDATE
FROM WIP_OPERATION WOP
         JOIN ILT_WIP_OPERATION IWOP ON WOP.WIPORDERNO = IWOP.WIPORDERNO
    AND WOP.WIPORDERTYPE = IWOP.WIPORDERTYPE
    AND WOP.OPRSEQUENCENO = IWOP.OPRSEQUENCENO
WHERE WOP.WIPORDERNO = @WipOrderNo
  AND WOP.WIPORDERTYPE = @WipOrderType
  AND WOP.OPRSEQUENCENO = @OprSequenceNo